# Generated by Django 3.2.9 on 2021-11-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211120_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
