# Generated by Django 3.2.9 on 2021-11-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_category_company_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_min',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
